### ISSUE TITLE
get_address()

### ISSUE THREAD

**Issue by tanupoo** [openschc/openschc#65]
get_address() in the l2 layer is not needed anymore, correct ?

**Comment by ltn22** [comment]
I'm not sure, i'm not sure to understand what this function is used for.

with UDP is it not necessary because we cannot use the L2 (here IP address+Port) as a rule identifier since the network change it with NAT. In that scenario we reduce the core to work with only one device identified as None.

with MQQT or HTTPS, websockets, the L2 address will be the devEUI so the core can manage plenty of devices and L2 @ will be necessary.

I think it is better to keep it, until Olivier MQTT is integrated

**Comment by tanupoo** [comment]
Thanks, removed.

**Comment by tanupoo** [comment]
done.
